### PR TITLE
Bump to Etherpad version 1.6.3 with node 8

### PR DESCRIPTION
**Pull request by wayglem**
Hi all, 
A lot has changed since etherpad 1.6.0 which was the latest version on this fork.
The main headache was making the travis build to be compliant with npm 5.

### CODE REVIEW

**Review by gberche-orange — CHANGES_REQUESTED** [review]
Thanks @wayglem for this contribution ! Looking forward to get this version bump and associated fixes (enabling pad edition following automatic reconnect and security fixes)

I see the upstream changes were rebased/squashed. I'd suggest to merge the original commits instead. That will make it easier to contribute etherpad-lite-cf specifics upstream in the future.

Also, can you please mention the tests that were performed (automated or manual tests) ?

In the future, we could use a SauceLabs ([free for opensource account](https://saucelabs.com/open-source)) along with a public CF deployment (e.g. [PWS](https://run.pivotal.io/faq/) with its trial account.) The PWS deployment will be only started during tests, and stopped in the other time  windows as to keep budget within trial $87.

Thanks again.

**Comment by wayglem** [comment]
Hello @gberche-orange,

Thanks for the review ! 
I messed up my Git history it's back to normal now.

I have tested it manually on two Cloud Foundry instances in our company it's working with mysql. Checked some plugins like padLister, table, set_pad_title and headings.
I also had to remove  ep_syntaxhighlighting and ep_colors since they are not maintained anymore and causes problems with node8. Will replace them in another PR with new ones.

I totally agree about the SauceLabs tests I will try to work on it soon :-)

**Comment by gberche-orange** [comment]
thanks @wayglem !

Feel free to merge and release a new version. We'll then be able to close related issues, and clean up draft [prereleases](https://github.com/cloudfoundry-community/etherpad-lite-cf/releases) that are not needed anymore.

**Review by gberche-orange — APPROVED** [review]

**Comment by ArthurHlt** [comment]
thanks for the work @wayglem, I've noticed some changes in `.travis.yml`:
- Change MyISAM to innodb is maybe overkill like etherpad is just storing things in key/value (value is a json btw). MyISAM is faster in this kind of usage and etherpad (ueberdb) doesn't seems to handle ACID. Can you revert to MyISAM ? (even if it's an old and not that much good engine, in this usecase it seems to be better)
- And also that you removed syntax highlighting, is it because it's not supported anymore ? 

About the rest, it's look good to me

**Comment by gberche-orange** [comment]
@ArthurHlt the MyIsam change was introduced as a temporary workaround for #6 and is unrelated to the 1.6.3 bump.

**Comment by wayglem** [comment]
@ArthurHlt yes the syntax highlightng is not supported I've oppened an issue to replace it

**Pull request merged**
